create table
  public.deletion_requests (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    user_id uuid not null,
    requested_at timestamp with time zone null,
    constraint deletion_requests_pkey primary key (id),
    constraint deletion_requests_user_id_fkey foreign key (user_id) references auth.users (id) on delete cascade
  ) tablespace pg_default; 