import React from "react";
export const CategoryVehicles = () => <h1>Vehicles Category Page</h1>;
export const CategoryElectronics = () => <h1>Electronics Category Page</h1>;
export const CategoryFurniture = () => <h1>Furniture Category Page</h1>;
export const CategoryClothing = () => <h1>Clothing Category Page</h1>;
export const CategoryTools = () => <h1>Tools Category Page</h1>;
export const CategorySportsOutdoors = () => <h1>Sports & Outdoors Category Page</h1>;
export const CategoryHomeGarden = () => <h1>Home & Garden Category Page</h1>;
export const CategoryToysGames = () => <h1>Toys & Games Category Page</h1>;
export const Favorites = () => <h1>Favorites Page</h1>;
export const Notifications = () => <h1>Notifications Page</h1>;
export const Cart = () => <h1>Cart Page</h1>;
export const Profile = () => <h1>Profile Page</h1>;
export const Sell = () => <h1>Post New Listing Page</h1>;
export const HowItWorks = () => <h1>How It Works Page</h1>;
export const WhyTomaShops = () => <h1>Why Choose TomaShops Page</h1>;
export const Safety = () => <h1>Safety Measures Page</h1>;
export const Shipping = () => <h1>Shipping & Handling Page</h1>;
export const Privacy = () => <h1>Privacy Policy Page</h1>;
export const Terms = () => <h1>Terms of Service Page</h1>;
export const Faq = () => <h1>FAQ Page</h1>; 